USE BASICINFO_MHID
SELECT * FROM BASICINFO
/*
SELECT * FROM CTCHECK
SELECT * FROM PNR
SELECT * FROM OLD
SELECT * FROM EXCHECK
SELECT * FROM SURGERY
SELECT * FROM PATHOLOGY
SELECT * FROM IMMUNOHISTOCHEMISTRY
SELECT * FROM GENETIC
SELECT * FROM FOLLOW_UP_RECORDS
*/